# Generated by Django 3.1 on 2020-09-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=15)),
                ('report_no', models.CharField(max_length=18)),
                ('client_info', models.CharField(max_length=100)),
                ('sample_type', models.CharField(max_length=150)),
            ],
        ),
    ]
