# Generated by Django 3.1 on 2020-09-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='sample_type',
            field=models.CharField(choices=[('CHEMICAL', 'Chemical'), ('MECHANICAL', 'Mechanical'), ('BOTH', 'Both')], max_length=150),
        ),
    ]
