# Generated by Django 3.1 on 2020-09-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainportal', '0002_auto_20200926_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='letter',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
